# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

# Set working directory
WORKDIR /app

# Copy package files
COPY package.json package-lock.json ./

# Install dependencies without running scripts (we'll run build later) 
RUN npm install --ignore-scripts

# Copy rest of source code
COPY . ./

# Build the project
RUN npm run build

# Expose port if needed, otherwise not exposing (MCP uses stdio)

# Start the server
CMD [ "npm", "start" ]
